# Generated by Django 3.0.4 on 2020-05-12 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_auto_20200512_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='onVersusId',
            new_name='onVersus',
        ),
        migrations.AlterField(
            model_name='follow',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
