# Generated by Django 3.0.4 on 2020-05-27 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versus', '0003_auto_20200520_2352'),
        ('follow', '0005_auto_20200524_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='onVersus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='versus.Versus'),
        ),
    ]
