# Generated by Django 3.0.4 on 2020-05-12 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('searchedUser', '0003_auto_20200512_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searcheduser',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
