# Generated by Django 3.0.4 on 2020-05-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=500)),
                ('victories', models.IntegerField()),
                ('date', models.DateField()),
                ('order', models.ImageField(upload_to='')),
                ('isMonetizedWeekly', models.BooleanField(default=False)),
                ('isMonetizedMonthly', models.BooleanField(default=False)),
                ('isMonetizedYearly', models.BooleanField(default=False)),
            ],
        ),
    ]
