# Generated by Django 3.0.4 on 2020-05-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200512_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='order',
            field=models.IntegerField(),
        ),
    ]
