# Generated by Django 3.0.4 on 2020-05-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200514_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='victories',
            field=models.IntegerField(null=True),
        ),
    ]
