# Generated by Django 3.0.4 on 2020-05-20 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votarkUser', '0013_auto_20200511_2141'),
        ('post', '0011_auto_20200520_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votarkUser.VotarkUser'),
        ),
    ]
