# Generated by Django 3.0.4 on 2020-05-11 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votarkUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votarkuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='votarkuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='votarkuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='votarkuser',
            name='password',
        ),
        migrations.AlterField(
            model_name='votarkuser',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
