# Generated by Django 3.0.4 on 2020-05-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votarkUser', '0002_auto_20200511_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='votarkuser',
            name='email',
            field=models.EmailField(default='sf@gmail.com', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='votarkuser',
            name='first_name',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='votarkuser',
            name='last_name',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='votarkuser',
            name='password',
            field=models.TextField(default='pas', max_length=100),
        ),
        migrations.AlterField(
            model_name='votarkuser',
            name='username',
            field=models.TextField(default='here', max_length=25, unique=True),
        ),
    ]
