# Generated by Django 3.0.4 on 2020-05-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votarkUser', '0005_auto_20200511_0527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votarkuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='votarkuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='votarkuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='votarkuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='votarkuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='votarkuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='votarkuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='votarkuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='votarkuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='votarkuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='votarkuser',
            name='first_name',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='votarkuser',
            name='last_name',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='votarkuser',
            name='password',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='votarkuser',
            name='username',
            field=models.TextField(max_length=25, unique=True),
        ),
    ]
