# Generated by Django 3.0.4 on 2020-05-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votarkUser', '0007_auto_20200511_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votarkuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='votarkuser',
            name='first_name',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='votarkuser',
            name='last_name',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='votarkuser',
            name='password',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='votarkuser',
            name='username',
            field=models.TextField(max_length=25, unique=True),
        ),
    ]
