# Generated by Django 3.0.4 on 2020-05-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votarkUser', '0008_auto_20200511_0706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votarkuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='votarkuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='votarkuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='votarkuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='votarkuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='votarkuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='votarkuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='votarkuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='votarkuser',
            name='user_permissions',
        ),
    ]
