# Generated by Django 3.0.4 on 2020-05-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votarkUser', '0010_auto_20200511_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votarkuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
