# Generated by Django 3.0.4 on 2020-05-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votarkUser', '0011_auto_20200511_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votarkuser',
            name='email',
            field=models.TextField(),
        ),
    ]
