# Generated by Django 3.0.4 on 2020-05-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votarkUser', '0012_auto_20200511_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votarkuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
