# Generated by Django 3.0.4 on 2020-05-23 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20200512_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
