# Generated by Django 3.0.4 on 2020-05-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200520_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
