# Generated by Django 3.0.4 on 2020-05-12 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic', '0001_initial'),
        ('hashtag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic.Topic'),
        ),
    ]
