# Generated by Django 3.0.4 on 2020-05-20 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20200514_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
