# Generated by Django 3.0.4 on 2020-05-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20200520_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='video',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
    ]
