# Generated by Django 3.0.4 on 2020-05-13 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('votarkUser', '0013_auto_20200511_2141'),
        ('post', '0005_auto_20200513_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedHashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.Post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votarkUser.VotarkUser')),
            ],
        ),
    ]
