# Generated by Django 3.0.4 on 2020-05-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchedHashtag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchedhashtag',
            old_name='post',
            new_name='hashtag',
        ),
    ]
