# Generated by Django 3.0.4 on 2020-05-25 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votarkUser', '0013_auto_20200511_2141'),
        ('post', '0015_auto_20200523_0926'),
        ('searchedHashtag', '0003_auto_20200520_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchedhashtag',
            name='hashtag',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
        migrations.AlterField(
            model_name='searchedhashtag',
            name='user',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='votarkUser.VotarkUser'),
        ),
    ]
