# Generated by Django 3.0.4 on 2020-05-25 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0002_hashtag_topic'),
        ('searchedHashtag', '0005_auto_20200525_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchedhashtag',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hashtag.Hashtag'),
        ),
    ]
