# Generated by Django 3.0.4 on 2020-05-12 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('votarkUser', '0013_auto_20200511_2141'),
        ('comment', '0001_initial'),
        ('versus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votarkUser.VotarkUser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='versus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='versus.Versus'),
        ),
    ]
