# Generated by Django 3.0.4 on 2020-05-12 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('post1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post1', to='post.Post')),
                ('post2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post2', to='post.Post')),
            ],
        ),
    ]
