# Generated by Django 3.0.4 on 2020-05-12 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('versus', '0001_initial'),
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='versus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='versus.Versus'),
        ),
    ]
